# Generated by Django 5.0.13 on 2025-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklkp',
            name='task',
            field=models.CharField(db_comment='Code for the task\n\nAPPLY check constraint to restrict to upper case', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
