# Generated by Django 5.2.6 on 2025-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0007_rename_polygon_polygonhistory_polygon_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='shp_processed_json',
        ),
        migrations.AddField(
            model_name='proposal',
            name='geojson_data_processed',
            field=models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry final result'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='geojson_data_processed_iters',
            field=models.JSONField(blank=True, null=True, verbose_name='Source Polygon Intersected with hist and split (multi) polygon geometry - all iterations'),
        ),
#        migrations.AlterField(
#            model_name='polygonhistory',
#            name='created_on',
#            field=models.DateTimeField(auto_now_add=True),
#        ),
#        migrations.AlterField(
#            model_name='polygonhistory',
#            name='updated_on',
#            field=models.DateTimeField(auto_now_add=True),
#        ),
    ]
